open Parser

let string_of_token (token : token) : string = match token with
  | ANY -> "'any' keyword"
  | ASSIGN -> "'=' symbol"
  | BOOL -> "'bool' keyword"
  | CASE -> "'case' keyword"
  | COLON -> "':' symbol"
  | COMMA -> "',' symbol"
  | DIV -> "'/' symbol"
  | DO -> "'do' keyword"
  | ELSE -> "'else' keyword"
  | EOF -> "end of file"
  | EOL -> "end of line"
  | EQUALS -> "'==' symbol"
  | FALSE -> "'false' keyword"
  | FOR -> "'for' keyword"
  | ID _ -> "identifier"
  | IF -> "'if' keyword"
  | IN -> "'in' keyword"
  | INT -> "'int' keyword"
  | INT_LIT _ -> "integer literal"
  | LAMBDA -> "'lambda' keyword"
  | LARROW -> "'<-' symbol"
  | LESS -> "'<' symbol"
  | LCURLY -> "'{' symbol"
  | LET -> "'let' keyword"
  | LPAREN -> "'(' symbol"
  | MINUS -> "'-' symbol"
  | NOT_EQUALS -> "'!=' symbol"
  | PLUS -> "'+' symbol"
  | QUESTION -> "'?' symbol"
  | GREATER -> "'>' symbol"
  | RARROW -> "'->' symbol"
  | RETURN -> "'return' keyword"
  | RINEQ -> "'>' symbol"
  | RCURLY -> "'}' symbol"
  | RPAREN -> "')' symbol"
  | SEMI -> "';' symbol"
  | SWITCH -> "'switch' keyword"
  | TIMES -> "'*' symbol"
  | TRUE -> "'true' keyword"
  | VOID -> "'void' keyword"
  | WHILE -> "'while' keyword"