open Parser

let string_of_token (token : token) : string = match token with
  | AMPERSAND -> "'&' symbol"
  | ANY -> "'any' keyword"
  | ARITY -> "'arity' keyword"
  | ASSIGN -> "'=' symbol"
  | BACKSLASH -> "'\\' symbol"
  | BANG -> "'!' symbol"
  | BOOL -> "'bool' keyword"
  | CARET -> "'^' symbol"
  | CASE -> "'case' keyword"
  | COLON -> "':' symbol"
  | COMMA -> "',' symbol"
  | CONST -> "'const' keyword"
  | DIV -> "'/' symbol"
  | DO -> "'do' keyword"
  | ELSE -> "'else' keyword"
  | EOF -> "end of file"
  | EOL -> "end of line"
  | EQUALS -> "'==' symbol"
  | FALSE -> "'false' keyword"
  | FOR -> "'for' keyword"
  | GREATER_EQUALS -> "'>=' symbol"
  | ID _ -> "identifier"
  | IF -> "'if' keyword"
  | IN -> "'in' keyword"
  | INT -> "'int' keyword"
  | INT_LIT _ -> "integer literal"
  | LESS -> "'<' symbol"
  | LESS_EQUALS -> "'<=' symbol"
  | LCURLY -> "'{' symbol"
  | LET -> "'let' keyword"
  | LOGICAL_AND -> "'&&' symbol"
  | LOGICAL_OR -> "'||' symbol"
  | LPAREN -> "'(' symbol"
  | MINUS -> "'-' symbol"
  | MODULO -> "'%' symbol"
  | MUT -> "'mut' keyword"
  | NOT_EQUALS -> "'!=' symbol"
  | PIPE -> "'|' symbol"
  | PLUS -> "'+' symbol"
  | PURE -> "'pure' keyword"
  | QUESTION -> "'?' symbol"
  | GREATER -> "'>' symbol"
  | RARROW -> "'->' symbol"
  | RETURN -> "'return' keyword"
  | RCURLY -> "'}' symbol"
  | RPAREN -> "')' symbol"
  | SEMI -> "';' symbol"
  | SWITCH -> "'switch' keyword"
  | TILDE -> "'~' symbol"
  | TIMES -> "'*' symbol"
  | TRUE -> "'true' keyword"
  | TYPE -> "'type' keyword"
  | TYPEOF -> "'typeof' keyword"
  | VOID -> "'void' keyword"
  | WHILE -> "'while' keyword"